# Configuration file for Mega-Linter
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
DEFAULT_BRANCH: master # Usually master or main
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE_LINTERS:
  - REPOSITORY_GIT_DIFF
  - JAVASCRIPT_STANDARD
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_GITLEAKS
JAVASCRIPT_DEFAULT_STYLE: prettier
FILTER_REGEX_EXCLUDE: (test_files)
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: true
