---
#######################################
# Start the job on all push to master #
#######################################
name: "Deploy beta"
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - "lib/**"
      - "README.md"
      - "CHANGELOG.mg"

permissions: read-all

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Deploy beta on NPM
    # Set the agent to run on
    runs-on: ubuntu-latest
    # Only run this on the main repo
    if: "!contains(github.event.head_commit.message, 'skip deploy')"
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      ##############################################################
      # Publish updated version of markdown-table-formatter on NPM #
      ##############################################################
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm run test:coverage
      - run: git config --global user.email "nicolas.vuillamy@gmail.com"
      - run: git config --global user.name "Nicolas.Vuillamy"
      - run: git status && git stash
      - run: npm version prerelease --preid="$(date '+%Y%m%d%H%M')"
      - run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
